services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "carlos"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "123456"
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com

databases:
  - name: n8n_db
    plan: free
    databaseName: n8ndb
    user: n8nuser